name: Smod build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
     - uses: actions/checkout@v2.4.0
     - uses: actions/setup-dotnet@v1.9.0
       with:
        dotnet-version: '4.7.2' 
        
     - name: Install dependencies
       run: dotnet restore
      
     - name: Build
       run: dotnet publish -c Release -o "${{github.workspace}}/Release"
      
     - name: Upload a Build Artifact
       uses: actions/upload-artifact@v2.0.1
       with:
        name: Smod
        path: ${{github.workspace}}/Release
